# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-13 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191113_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
